from typing import Dict

ROUTING_LABEL = "Selecting the right specialist agent…"
LLM_CALL_LABEL = "Analyzing your request…"
SYNTHESIS_LABEL = "Putting together your answer…"
DEFAULT_STATUS_LABEL = "Working on it…"

TOOL_STATUS_LABELS: Dict[str, str] = {
    # billing
    "lookup_product": "Checking the price list…",
    "get_recent_bills": "Reviewing recent bills…",
    "get_bill_by_number": "Fetching bill details…",
    "get_daily_token_count": "Checking today's token counter…",
    "get_hold_bills": "Checking held/parked bills…",
    "get_customer_order_history": "Fetching customer order history…",
    "get_bill_payment_summary": "Aggregating billing payment collections…",
    "propose_create_bill": "Drafting the customer bill…",
    "propose_split_payment_bill": "Drafting split-payment bill…",
    "propose_hold_bill": "Holding/parking draft order…",
    "propose_recall_hold_bill": "Recalling parked bill for payment…",
    "propose_apply_bill_discount": "Applying bill discount…",
    "propose_void_bill": "Reviewing the bill to void…",
    # inventory
    "get_inventory_status": "Checking stock levels…",
    "list_low_stock_items": "Finding low stock alerts…",
    "get_stock_valuation": "Calculating stock valuation…",
    "get_stock_consumption_rate": "Calculating stock usage rate & days left…",
    "get_inventory_logs": "Reviewing stock adjustment audit logs…",
    "propose_adjust_stock": "Preparing a stock adjustment…",
    "propose_bulk_stock_adjustment": "Preparing batch stock adjustment…",
    "propose_update_threshold": "Updating alert threshold…",
    "propose_create_raw_material": "Adding new raw material to inventory…",
    "propose_update_inventory_item": "Updating inventory item…",
    "propose_reset_stock_count": "Reconciling physical stock count…",
    # product
    "search_products": "Searching product catalog…",
    "get_categories_and_groups": "Loading categories and groups…",
    "get_category_list": "Listing registered categories…",
    "get_group_list": "Listing item groups…",
    "get_product_details": "Fetching product details & recipe…",
    "propose_create_product": "Adding the new product…",
    "propose_update_product": "Updating the menu item…",
    "propose_variation_update": "Updating product variations…",
    "propose_group_reorder": "Updating group display order…",
    "propose_toggle_group_status": "Toggling the item group…",
    "propose_create_category": "Creating new menu category…",
    "propose_create_item_group": "Creating new item group…",
    "propose_update_category": "Updating category…",
    "propose_bulk_update_prices": "Updating menu prices in bulk…",
    "propose_bulk_toggle_products": "Toggling product availability in bulk…",
    "propose_delete_category": "Preparing category deletion…",
    "propose_delete_item_group": "Preparing item group deletion…",
    "propose_bulk_delete_categories": "Preparing bulk category deletion…",
    "propose_bulk_delete_item_groups": "Preparing bulk item group deletion…",
    # worker
    "list_workers": "Checking staff records…",
    "get_worker_attendance": "Checking daily attendance…",
    "get_attendance_summary": "Summarizing month-to-date attendance…",
    "get_pending_payroll": "Calculating pending payroll breakdown…",
    "calculate_worker_salary": "Working out the salary breakdown…",
    "get_worker_advances": "Reviewing worker salary advances…",
    "list_worker_roles": "Listing staff designations & roles…",
    "propose_create_worker": "Setting up the new worker…",
    "propose_update_worker": "Updating worker profile…",
    "propose_mark_attendance": "Marking worker attendance…",
    "propose_bulk_mark_attendance": "Marking staff attendance in bulk…",
    "propose_record_advance": "Recording salary advance…",
    "propose_create_worker_role": "Registering new staff role…",
    # expense
    "list_expense_types": "Checking expense categories…",
    "list_recent_expenses": "Reviewing recent expenses…",
    "get_expense_category_breakdown": "Aggregating expense breakdown…",
    "get_expense_by_id": "Fetching expense voucher details…",
    "get_recurring_expense_forecast": "Forecasting monthly operational expenses…",
    "propose_log_expense": "Logging the expense voucher…",
    "propose_bulk_log_expenses": "Recording expense vouchers in bulk…",
    "propose_update_expense": "Updating expense voucher…",
    "propose_expense_type": "Registering new expense category…",
    "propose_update_expense_type": "Updating expense category…",
    "propose_delete_expense": "Preparing expense voucher deletion…",
    "propose_delete_expense_type": "Preparing expense category deletion…",
    "propose_bulk_delete_expenses": "Preparing bulk expense deletion…",
    # analytics
    "get_sales_kpi_summary": "Looking at sales KPIs…",
    "get_sales_trend": "Analyzing multi-day sales trends…",
    "get_hourly_footfall": "Analyzing hourly footfall & orders…",
    "get_top_selling_products": "Checking your best sellers…",
    "get_payment_mode_breakdown": "Analyzing payment breakdown…",
    "get_category_sales_breakdown": "Aggregating sales by category…",
    "get_order_type_breakdown": "Comparing Dine-In vs Takeaway vs Delivery…",
    "get_peak_days_analysis": "Analyzing peak earning days of the week…",
    "get_dead_stock_report": "Finding slow-moving & inactive menu items…",
    "get_profit_margin_analysis": "Computing profit margin & cost ratios…",
    "propose_export": "Preparing data report export…",
    # reminder
    "list_reminders": "Checking pending reminders…",
    "get_unread_notification_count": "Checking notifications & alerts…",
    "list_notifications": "Loading notification inbox…",
    "propose_create_reminder": "Setting the reminder…",
    "propose_bulk_create_reminders": "Scheduling checklist reminders in bulk…",
    "propose_snooze_reminder": "Snoozing the reminder…",
    "propose_complete_reminder": "Completing the reminder…",
    "propose_update_reminder": "Updating reminder schedule…",
    "propose_delete_reminder": "Preparing reminder deletion…",
    "delete_notification": "Deleting notification…",
    "propose_mark_all_notifications_read": "Dismissing all notifications…",
    "propose_bulk_delete_reminders": "Preparing bulk reminder deletion…",
    "restore_deleted_item": "Restoring deleted record…",
    "restore_last_bulk_delete": "Restoring bulk deletion batch…",
}


def get_status_label(tool_name: str) -> str:
    """Return a natural, jargon-free status string for any tool."""
    return TOOL_STATUS_LABELS.get(tool_name, DEFAULT_STATUS_LABEL)
