"""Initial migration

Revision ID: 7033b836508d
Revises: 
Create Date: 2026-04-19 13:29:07.246084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7033b836508d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('worker_id'),
    schema='worker'
    )
    op.create_table('advances',
    sa.Column('advance_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.workers.worker_id'], ),
    sa.PrimaryKeyConstraint('advance_id'),
    schema='worker'
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.workers.worker_id'], ),
    sa.PrimaryKeyConstraint('attendance_id'),
    schema='worker'
    )
    with op.batch_alter_table('attendance', schema='worker') as batch_op:
        batch_op.create_index('idx_attendance_worker_date', ['worker_id', 'date'], unique=False)

    op.create_table('salary_payments',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('advance_deduction', sa.Float(), nullable=True),
    sa.Column('final_salary', sa.Float(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.workers.worker_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    schema='worker'
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index('idx_bills_created_at_no', ['created_at', 'bill_no'], unique=False)
        batch_op.create_index('idx_bills_status', ['status'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('idx_expenses_date', ['date'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_expense_worker'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['worker_id'], referent_schema='worker')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_products_active', ['active'], unique=False)
        batch_op.create_index('idx_products_category_id', ['category_id'], unique=False)

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_reminder_time'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.create_index('idx_reminder_status_time', ['status', 'reminder_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('idx_reminder_status_time')
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_reminder_time'), ['reminder_time'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_products_category_id')
        batch_op.drop_index('idx_products_active')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_expense_worker'), 'workers', ['worker_id'], ['worker_id'], referent_schema='worker', ondelete='SET NULL')
        batch_op.drop_index('idx_expenses_date')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index('idx_bills_status')
        batch_op.drop_index('idx_bills_created_at_no')

    op.drop_table('salary_payments', schema='worker')
    with op.batch_alter_table('attendance', schema='worker') as batch_op:
        batch_op.drop_index('idx_attendance_worker_date')

    op.drop_table('attendance', schema='worker')
    op.drop_table('advances', schema='worker')
    op.drop_table('workers', schema='worker')
    # ### end Alembic commands ###
