"""add worker and expense types

Revision ID: add_worker_and_expense_types
Revises: add_takeaway_price
Create Date: 2025-01-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_worker_and_expense_types'
down_revision = 'add_takeaway_price'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        'expense_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    op.create_table(
        'worker_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    # Add worker_type_id column to workers table
    op.add_column('workers', sa.Column('worker_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_workers_worker_type_id', 'workers', 'worker_types', ['worker_type_id'], ['id'])
    
    # Insert default worker types (only if table is empty)
    op.execute("""
        INSERT INTO worker_types (name, description, is_active, created_at, updated_at)
        SELECT * FROM (VALUES
            ('Chef', 'Kitchen staff responsible for food preparation', 1, datetime('now'), datetime('now')),
            ('Waiter', 'Front-of-house staff serving customers', 1, datetime('now'), datetime('now')),
            ('Manager', 'Supervisory staff managing operations', 1, datetime('now'), datetime('now')),
            ('Cleaner', 'Staff responsible for cleaning and maintenance', 1, datetime('now'), datetime('now')),
            ('Delivery', 'Staff handling food delivery', 1, datetime('now'), datetime('now'))
        ) AS temp(name, description, is_active, created_at, updated_at)
        WHERE NOT EXISTS (SELECT 1 FROM worker_types LIMIT 1)
    """)
    
    # Insert default expense types (only if table is empty)
    op.execute("""
        INSERT INTO expense_types (name, description, is_active, created_at, updated_at)
        SELECT * FROM (VALUES
            ('Utilities', 'Electricity, water, gas bills', 1, datetime('now'), datetime('now')),
            ('Rent', 'Monthly rent or lease payments', 1, datetime('now'), datetime('now')),
            ('Supplies', 'Food ingredients and consumables', 1, datetime('now'), datetime('now')),
            ('Equipment', 'Kitchen equipment and tools', 1, datetime('now'), datetime('now')),
            ('Maintenance', 'Repair and maintenance costs', 1, datetime('now'), datetime('now')),
            ('Marketing', 'Advertising and promotional expenses', 1, datetime('now'), datetime('now')),
            ('Insurance', 'Business insurance premiums', 1, datetime('now'), datetime('now')),
            ('Transportation', 'Vehicle and fuel costs', 1, datetime('now'), datetime('now'))
        ) AS temp(name, description, is_active, created_at, updated_at)
        WHERE NOT EXISTS (SELECT 1 FROM expense_types LIMIT 1)
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_constraint('fk_workers_worker_type_id', 'workers', type_='foreignkey')
    op.drop_column('workers', 'worker_type_id')
    op.drop_table('worker_types')
    op.drop_table('expense_types')
    # ### end Alembic commands ###
